theme: jekyll-theme-minimal
title: Ayşe Gül Çiftçi
description: C# Programlama Temelleri | [LinkedIn Profilim](https://www.linkedin.com/in/ay%C5%9Fe-g%C3%BCl-%C3%A7ift%C3%A7i-492879298)
logo: https://github.com/aysegul-codes.png
show_downloads: false
