theme: jekyll-theme-minimal
title: Ayşe Gül Çiftçi
description: C# Programlama Temelleri | [LinkedIn Profilim](https://www.linkedin.com/in/ayşe-gül-çiftçi-492879298)
logo: https://github.com/aysegul-codes.png
show_downloads: false
